# Generated by Django 6.0 on 2025-12-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
